# Generated by Django 4.2.15 on 2025-07-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="dataTable",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("COMPUTERNAME", models.CharField(max_length=255)),
                ("OS", models.CharField(max_length=255)),
                ("USERDOMAIN", models.CharField(max_length=255)),
                ("REMOTE_HOST", models.CharField(max_length=255)),
                ("QUERY_STRING", models.TextField()),
                ("HTTP_USER_AGENT", models.TextField()),
                ("GENERATED_KEYWORDS", models.TextField()),
                ("GENERATED_COUNTS", models.TextField(blank=True, null=True)),
                ("CONTENT_LENGTH", models.IntegerField(blank=True, null=True)),
                ("remote_addr", models.GenericIPAddressField(blank=True, null=True)),
                ("KEYWORD", models.CharField(max_length=255)),
            ],
        ),
    ]
